/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package urirfid.views;

import javax.swing.JDialog;
import javax.swing.JOptionPane;
import urirfid.models.Location;

/**
 *
 * @author Enayet
 */
public class LocationFrameView extends javax.swing.JFrame {

    /**
     * Creates new form LocationFrameView
     */
    public LocationFrameView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        locationDetailView = new urirfid.views.LocationDetailView();
        mapView = new urirfid.views.MapView();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(locationDetailView, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mapView, javax.swing.GroupLayout.PREFERRED_SIZE, 1500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(locationDetailView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mapView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private urirfid.views.LocationDetailView locationDetailView;
    private urirfid.views.MapView mapView;
    // End of variables declaration//GEN-END:variables

    public Location currentLocation;
    private JDialog dialog;

    public void updateCurrentLocation(Location l){
        
        if (l.id.equals("no_tag"))
        {
//            JOptionPane optionPane = new JOptionPane("Please Bring a Location Tag", JOptionPane.WARNING_MESSAGE);
//            dialog = optionPane.createDialog("Warning!");
//            dialog.setAlwaysOnTop(true);
//            dialog.setVisible(true);
        }
        else
        {
            if (this.dialog != null)
            {
                this.dialog.dispose();
            }
                
            this.currentLocation = l;
            locationDetailView.updateCurrentLocation(l);
            mapView.updateCurrentLocation(l);
            this.invalidate();
            this.repaint();
            
        }
    }
}
